services:
  unbound:
    image: mvance/unbound:latest
    platform: linux/arm64
    container_name: unbound
    restart: unless-stopped
    ports:
      - "5335:53/udp"
    environment:
      - LISTEN_PORT=5335
      - CUSTOM_RESOLVER_CONF=/opt/unbound/etc/unbound/unbound.conf
    volumes:
      - ./unbound-conf:/opt/unbound/etc/unbound:ro
    networks:
      pihole_net:
        ipv4_address: 172.22.0.10
    # Explicit platform set to avoid warnings
    # Adjust image if you want another version

  tailscale:
    image: tailscale/tailscale:latest
    platform: linux/arm64
    container_name: tailscale-pihole
    hostname: pihole-server
    environment:
      - TS_AUTHKEY=${AUTHKEY}  # Make sure this is set in environment or GitHub secret
      - TS_EXTRA_ARGS=--accept-dns=false --advertise-tags=tag:dns
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 172.22.0.20

  pihole:
    image: pihole/pihole:latest
    platform: linux/arm64
    container_name: pihole
    depends_on:
      - unbound
      - tailscale
    network_mode: "service:tailscale"
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: "admin123"
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 172.22.0.10#5335
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  tailscale-data:
    driver: local

