name: Pi-hole + Unbound + Tailscale CI/CD (Ubuntu)

on:
  push:
    branches: [master]  # or main, set this to your default branch
  pull_request:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      AUTHKEY: ${{ secrets.AUTHKEY }}  # Your Tailscale auth key stored in GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (dig tool)
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      - name: Validate Docker Compose configuration
        run: docker compose -f docker-compose.yml config -q

      - name: Validate Unbound config syntax
        run: |
          docker run --rm -v $PWD/unbound-conf/unbound.conf:/etc/unbound/unbound.conf:ro \
          mvance/unbound unbound-checkconf /etc/unbound/unbound.conf

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      - name: Start Pi-hole + Unbound + Tailscale services
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services to start
        run: sleep 20

      - name: Update Pi-hole blocklists (gravity)
        run: docker exec pihole pihole -g

      - name: Test DNS resolution via Unbound
        run: dig @127.0.0.1 -p 5335 google.com +short

      - name: Verify Pi-hole blocks an ad domain
        run: |
          BLOCKED_IP="0.0.0.0"
          TEST_DOMAIN="doubleclick.net"
          QUERY_RESULT=$(docker exec pihole dig +short $TEST_DOMAIN)
          echo "Query result for $TEST_DOMAIN: $QUERY_RESULT"
          if [[ "$QUERY_RESULT" != "$BLOCKED_IP" ]]; then
            echo "ERROR: Pi-hole is not blocking $TEST_DOMAIN as expected."
            exit 1
          fi
          echo "✅ Pi-hole successfully blocks $TEST_DOMAIN."

      - name: Security vulnerability scan for Pi-hole image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pihole/pihole:latest
          exit-code: 0

      - name: Cleanup Docker Compose services
        if: always()
        run: docker compose -f docker-compose.yml down -v

