name: Pi-hole + Unbound + Tailscale CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Verify Docker & Compose versions (sanity check)
      - name: Verify Docker and Compose
        run: |
          docker --version
          docker compose version

      # 3. Validate docker-compose config
      - name: Validate Docker Compose
        run: docker compose -f docker-compose.yml config -q

      # 4. Validate Unbound config syntax
      - name: Validate Unbound config
        run: |
          docker run --rm -v $PWD/unbound-conf:/opt/unbound/etc/unbound:ro \
          mvance/unbound unbound-checkconf /opt/unbound/etc/unbound/unbound.conf

      # 5. Build Docker images
      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      # 6. Start services
      - name: Start Pi-hole + Unbound + Tailscale
        run: docker compose -f docker-compose.yml up -d

      # 7. Wait for containers to be ready
      - name: Wait for services
        run: sleep 20

      # 8. Update Pi-hole blocklists (gravity)
      - name: Update Pi-hole blocklists
        run: docker exec pihole pihole -g

      # 9. Test DNS resolution via Unbound
      - name: Test DNS resolution via Unbound
        run: dig @127.0.0.1 -p 5335 google.com +short

      # 10. Verify Pi-hole blocks ad domain
      - name: Verify Pi-hole blocks ad domain
        run: |
          BLOCKED_IP="0.0.0.0"
          TEST_DOMAIN="doubleclick.net"
          QUERY_RESULT=$(docker exec pihole dig +short $TEST_DOMAIN)
          echo "Query result for $TEST_DOMAIN: $QUERY_RESULT"
          if [[ "$QUERY_RESULT" != "$BLOCKED_IP" ]]; then
            echo "❌ ERROR: Pi-hole is not blocking $TEST_DOMAIN as expected."
            exit 1
          fi
          echo "✅ Pi-hole successfully blocks $TEST_DOMAIN."

      # 11. Security scan (Trivy)
      - name: Security scan for Pi-hole image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pihole/pihole:latest
          exit-code: 0  # Don't fail build on vulnerabilities yet

      # 12. Cleanup
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.yml down -v

