name: Build, Test, Deploy, and Push Changes to GitHub

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the 'main' branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Set up QEMU for multi-platform support
    - name: Set up QEMU for multi-platform
      uses: docker/setup-qemu-action@v2

    # Step 4: Cache Docker layers for faster builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Step 5: Build Docker images using Docker Compose
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.yml build

    # Step 6: Run tests and start containers (optional)
    - name: Run tests and start containers
      run: |
        docker-compose -f docker-compose.yml up -d  # Start containers
        docker-compose -f docker-compose.yml logs  # Check logs for issues

    # Step 7: Push Docker images to Docker Hub (optional)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker-compose -f docker-compose.yml push

  push_to_github:
    needs: build  # Ensure this job runs only after the build job has finished
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/che
